import type { Vault } from './types';

export const vaults: Vault[] = [
  {
    id: 'earn-eth-lido-mellow',
    name: 'earnETH Lido v3',
    strategyTags: ['DeFi'],
    tvl: '62.7K ETH',
    tvlUsd: '~$129M',
    apr7d: '5%',
    collateralAssets: ['ETH', 'wETH', 'wstETH', 'strETH', 'DVstETH', 'GG'],
    chain: 'Ethereum',
    platform: 'Lido & Mellow',
    platformIcons: ['https://lido.fi/favicon.ico', 'https://mellow.finance/favicon.ico'],
    riskCurator: 'Mellow',
    riskCuratorIcon: 'https://mellow.finance/favicon.ico',
    riskCuratorUrl: 'https://mellow.finance/',
    navAdmin: 'Lambda',
    navAdminUrl: 'https://lambda.p2p.org',
    navAdminLogo: 'https://lambda.p2p.org/favicon.ico',
    navAudit: null,
    fees: '15%',
    strategyScore: 'A',
    navAdminScore: 'A+',
    platformScore: 'A+',
    institutionalRiskScore: 'AAA+',
    allocations: 'public',
    usersScore: 'Institutions',
    category: 'A',
  },
  {
    id: 'p2p-eth-plus',
    name: 'P2P ETH+',
    strategyTags: ['DeFi+CeFi'],
    tvl: '15K ETH',
    tvlUsd: '~$30M',
    apr7d: '4.7%',
    collateralAssets: ['ETH', 'wETH', 'wstETH'],
    chain: 'Ethereum',
    platform: 'Fluid',
    platformIcons: ['https://www.google.com/s2/favicons?domain=fluid.instadapp.io&sz=32'],
    platformUrl: 'https://fluid.io/',
    riskCurator: 'EdgeCapital',
    riskCuratorIcon: 'https://edgecapital.xyz/favicon.svg',
    riskCuratorUrl: 'https://edgecapital.xyz/',
    navAdmin: 'Lambda',
    navAdminUrl: 'https://lambda.p2p.org',
    navAdminLogo: 'https://lambda.p2p.org/favicon.ico',
    navAudit: null,
    fees: '20%',
    strategyScore: 'A',
    navAdminScore: 'A+',
    platformScore: 'A+',
    institutionalRiskScore: 'AAA+',
    allocations: 'public',
    usersScore: 'Institutions',
    category: 'A',
  },
  {
    id: 'p2p-usd-plus',
    name: 'P2P USD++',
    strategyTags: ['DeFi+CeFi'],
    tvl: '10M USD',
    tvlUsd: '~$30M',
    apr7d: '5.5%',
    collateralAssets: ['USDC', 'USDT'],
    chain: 'Ethereum',
    platform: 'UltraYield',
    platformIcons: ['https://ultrayield.app/favicon.ico'],
    platformUrl: 'https://ultrayield.app/',
    riskCurator: 'EdgeCapital',
    riskCuratorIcon: 'https://edgecapital.xyz/favicon.svg',
    riskCuratorUrl: 'https://edgecapital.xyz/',
    navAdmin: 'Curator',
    navAdminUrl: 'https://edgecapital.xyz/',
    navAdminLogo: 'https://edgecapital.xyz/favicon.svg',
    navAudit: 'navfundservices.com',
    navAuditUrl: 'http://navfundservices.com/',
    navAuditLogo: 'https://www.navfundservices.com/_next/image?url=%2Fimages%2Fsquare-logo-blue.png&w=256&q=75',
    fees: '20%',
    strategyScore: 'B',
    navAdminScore: 'A',
    platformScore: 'B',
    institutionalRiskScore: 'BBB+',
    allocations: 'private',
    usersScore: 'Institutions',
    category: 'B',
  },
  {
    id: 'earn-usdc-lido-mellow',
    name: 'earnUSDC Lido v3',
    strategyTags: ['DeFi'],
    tvl: '6.6M USDC',
    tvlUsd: '~$6.6M',
    apr7d: '5.5%',
    collateralAssets: ['USDC', 'USDT'],
    chain: 'Ethereum',
    platform: 'Lido & Mellow',
    platformIcons: ['https://lido.fi/favicon.ico', 'https://mellow.finance/favicon.ico'],
    riskCurator: 'Mellow',
    riskCuratorIcon: 'https://mellow.finance/favicon.ico',
    riskCuratorUrl: 'https://mellow.finance/',
    navAdmin: 'Lambda',
    navAdminUrl: 'https://lambda.p2p.org',
    navAdminLogo: 'https://lambda.p2p.org/favicon.ico',
    navAudit: null,
    fees: '15%',
    strategyScore: 'A-',
    navAdminScore: 'A+',
    platformScore: 'A+',
    institutionalRiskScore: 'AAA-',
    allocations: 'public',
    usersScore: 'Enterprise LP',
    category: 'A',
  },
  {
    id: 'your-usdc',
    name: 'yourUSD vault',
    strategyTags: ['DeFi'],
    tvl: '10M USDC',
    tvlUsd: '~$10M',
    apr7d: '7%',
    collateralAssets: ['USDC', 'USDT'],
    chain: 'Arbitrum',
    platform: 'Upshift',
    platformIcons: ['https://www.google.com/s2/favicons?domain=upshift.finance&sz=32'],
    platformUrl: 'https://upshift.finance',
    riskCurator: 'KPK',
    riskCuratorIcon: 'https://www.google.com/s2/favicons?domain=kpk.io&sz=32',
    riskCuratorUrl: 'https://kpk.io/',
    navAdmin: 'pennyworks.com',
    navAdminUrl: 'https://pennyworks.com',
    navAudit: null,
    fees: '10%',
    strategyScore: 'C',
    navAdminScore: 'C',
    platformScore: 'B',
    institutionalRiskScore: 'CCC+',
    allocations: 'private',
    usersScore: 'Whales',
    category: 'C',
  },
];
